### ISSUE TITLE
import CoCMessageDecoder error.

### ISSUE THREAD

**Issue by TheHolyLoli** [clugh/coc-proxy#1]
hello,i saw your prefect job and downloaded the source code to try.but i after installing requirements,i dont know how to run and use?
also message folder is empty so there is nothing to be imported in proxy.py:
    `proxy.py, line 3, in <module>`
    `from coc.message.decoder import CoCMessageDecoder`
    `ImportError: No module named 'coc.message.decoder'`

**Comment by 123456abcdef** [comment]
If you check the structure of this repo you will see that it links to 2 other repos. The folder `message` links to `coc-messages-python` and the folder `definitions` links to `coc-messages`. Get all 3 repos and put them together. Then it will work with no problem!

**Comment by clugh** [comment]
When you clone the source with `git`, you have to initialize the submodules:

https://git-scm.com/book/en/v2/Git-Tools-Submodules#Cloning-a-Project-with-Submodules

**Comment by goldbi** [comment]
@clugh Hey, Can you add me on skype?
hiimeiffel
Eiffel from ultrapowa community.
