### ISSUE TITLE
Failed decrypt

### ISSUE THREAD

**Issue by kirill-782** [clugh/coc-proxy#14]
`
listening on 0.0.0.0:9339 ...
connection from 192.168.0.105:56648 ...
connected to 54.160.120.142:9339 ...
10100 Error: 'Message definition missing (10100).'
10100 27740000480000000000010000000900000008000000000000014c00000028613038373039
35633838333237366262386362376134346162636331313063316631383361306432000000020000
0002
20100 Error: 'Message definition missing (20100).'
20100 4e8400001c0000000000185e6768bdc2de989d3ae94c081ad153ba7fdd5fcef6b86c63
Failed to decrypt the message (server, 10101).
connection from 192.168.0.105:56648 closed ...
connection to 54.160.120.142:9339 closed ...`

**Comment by clugh** [comment]
Without running a test, my guess is that you didn't initialize/download the submodules.  Feel free to reopen if you're still working on it.
