### ISSUE TITLE
8.709.2 working?

### ISSUE THREAD

**Issue by zyxwvuts** [clugh/coc-proxy#18]
Is anybody's proxy working after 8.709.2?  After the update, my project never receives the LoginOk (20104) message after sending the Login (10101) message.  I figure it something specific to my code (which is pretty different from what's here), but wanted to make sure that this project is working properly for someone.

**Comment by FICTURE7** [comment]
It should be. Be sure to use the latest public key in the proxy and  patch the `libg.so` files.

You can find the latest key and offsets at #17.

**Comment by zyxwvuts** [comment]
Thanks, I forgot to update my public key.
