### ISSUE TITLE
Clash Royale Support

### ISSUE THREAD

**Issue by 123456abcdef** [clugh/coc-proxy#3]
Hi,
don't know what your plans about CR are, but I want to publish this somewhere in your repos, because it is all based on your work.

`Clash Royale v1.2.3`
`Server: game.clashroyaleapp.com:9339`
`Key: ba105f0d3a099414d154046f41d80cf122b49902eab03b78a912f3c66dba2c39 (hex)`
`Offset x86: 5419036 (dec)`
`Offset arm: 3776540 (dec)`

The x86 version works just fine with my proxy, I couldn't test the offset of the arm version.
Hope it helps!

**Comment by clugh** [comment]
I currently have no intention of supporting CR.  I'd suggest a combined or CR-specific fork to house that info.

That's interesting to know, though, that the two function similarly under the hood.  I guess it makes sense not to reinvent the wheel.  clanner has some information about Hay Day in the old cocdp wiki, so I'm guessing all their games have a bunch of similarities.
