### ISSUE TITLE
Proxy needs update for version 8.212.3 

### ISSUE THREAD

**Issue by d3death** [clugh/coc-proxy#4]
Update arrived on March 21, 2016

**Comment by FICTURE7** [comment]
Hmm, LoginFailedMessage appears to be unencrypted now.

**Comment by d3death** [comment]
@FICTURE7 do you know keys offsets for this version?

**Comment by FICTURE7** [comment]
Am not too sure about it, but I think its at `5E7019` for the `x86` version am getting this `0c52db12ba1c9dd809b8934a535f428a91b7b61e15ab469e42b9614c76a32501`. I was unable to decrypt any message so far might be because I am patching the wrong thing.

**Comment by FICTURE7** [comment]
Alright! I got it, the offset is actually `5E7018` for the `x86` version and it returns this `150c52db12ba1c9dd809b8934a535f428a91b7b61e15ab469e42b9614c76a325`. I was able to run the server without any issues.

**Comment by d3death** [comment]
hmm. for some reaons its stuck for me at after  packet 10101. pretty sure i'm patching at correct place since `xxd -p -c 32 key-backup.bin` prints
`150c52db12ba1c9dd809b8934a535f428a91b7b61e15ab469e42b9614c76a325` which matches yours. will look more into it. any chance u can get offset and key for arm too?

**Comment by d3death** [comment]
okay i had forgotten to change in code. works now

**Comment by clugh** [comment]
Thanks, @FICTURE7, the [Keys](https://github.com/clugh/coc-proxy/wiki/Keys) and [Key Offsets](https://github.com/clugh/coc-proxy/wiki/Key-Offsets) wiki pages have been updated.

> Hmm, LoginFailedMessage appears to be unencrypted now.

It is unencrypted when it is received instead of 20100; otherwise, it is encrypted.

**Comment by FICTURE7** [comment]
Owh, I see, was not aware of it.
