### ISSUE TITLE
keys and offsets needed for version 8.212.9 

### ISSUE THREAD

**Issue by d3death** [clugh/coc-proxy#5]
an optional update came out recently

**Comment by 123456abcdef** [comment]
Key: `469B704E7F6009BA8FC72E9B5C864C8E9285A755C5190F03F5C74852F6D9F419`
Offset arm: `4280344` (dec)
Offset x86: `6189080` (dec)
URL arm : `3534513` (dec)
URL x86: `4768816` (dec)

**Comment by d3death** [comment]
just wondering if someone can write a short tutorial on would 1 go on finding these offsets and keys

**Comment by 123456abcdef** [comment]
I can show you my cheap way how to do it :P.

Assuming Supercell won't change it's building process of the apk until the next big update, I think it is save to presume that the compiled libg.so will always have a similar structure (Please correct me if I'm wrong). That said, the key we are looking for will be roughly at the same offset +/- the addition/changes of the update.
1. Open the libg.so in IDA (the free version is sufficient). Jump to the offset of the old key. What we are looking for is the beginning of the closest `.data` section (marked with 1, also note the red rectangle on the bar at the top). Now look for a 32 byte long sequence, until now the first sequence always was the key (marked with 2).
   ![ida](https://cloud.githubusercontent.com/assets/16580931/14061210/f8702116-f37a-11e5-9309-59ad3b53f2b9.png)
2. Open the libg.so in your favourite hex editor and search for the 32 byte data sequence you extracted from IDA. Write down the offset and patch like @clugh wrote or simply overwrite the key with our custom key directly in your hex editor.
   ![hex](https://cloud.githubusercontent.com/assets/16580931/14061239/8a0e96ca-f37b-11e5-966a-03cde006b305.png)
3. Test your modded libg.so!

**Comment by clugh** [comment]
Thanks, @123456abcdef.

The [Keys](https://github.com/clugh/coc-proxy/wiki/Keys), [Key Offsets](https://github.com/clugh/coc-proxy/wiki/Key-Offsets), and [URL Offsets](https://github.com/clugh/coc-proxy/wiki/URL-Offsets) pages have all been updated.
