### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by clugh** [clugh/coc-proxy#6]
While working on [`coc-patcher`](https://github.com/clugh/coc-patcher), I did a little fiddling around with Windows, so I figured I'd take a look for `coc-proxy`, as well.  Turns out it was relatively painless to get working. Here are the steps:
1. Install [Python 3.5.x](https://www.python.org/downloads/windows/)
   
   **Note:** If you aren't working with other versions of Python, do yourself a favor and check the option to add it to your PATH.
2. Install `pywin32`:
   
   ```
    pip install pypiwin32
   ```
3. Install `zope.interface`:
   
   ```
    pip install zope.interface
   ```
4. Install `twisted` from the `moar-windows-8025-6` branch:
   
   ```
   git clone https://github.com/twisted/twisted.git
   cd twisted
   git checkout moar-windows-8025-6
   python setup3.py install
   ```
   
   **Warning:** Be sure to check out the ticket [here](https://twistedmatrix.com/trac/ticket/8025). At a glance, it appears to be mostly about code formatting, but I only skimmed it and may have missed something important.
5. Install `pynacl`:
   
   ```
   pip install pynacl
   ```
6. Install [Visual Studio Community](https://www.visualstudio.com/downloads/download-visual-studio-vs)
   
   **Note:** Be sure to check Visual C++.
7. Install `pyblake2`
   
   ```
   pip install pyblake2
   ```

**Comment by FICTURE7** [comment]
I find it funny, because i was working on the same thing but in C# xD.

**Comment by clugh** [comment]
Which part? a patcher for the APK? Great minds and all.

**Comment by FICTURE7** [comment]
Yeah a patcher for the apk, It dumps the libg.so stuff and patches them and sign the new apk with `signapk.jar`, but yours is more complete and fancier.

**Comment by clugh** [comment]
I looked at `signapk.jar`, but I didn't like that it didn't give the option for custom keys.

**Comment by FICTURE7** [comment]
Yeah, signing the apk with `zipalign.jar`, `keytool.jar` and `jarsigner.jar` is neater than doing it with `signapk.jar`.
