### ISSUE TITLE
Failed to decrypt the message

### ISSUE THREAD

**Issue by Izwal** [clugh/coc-proxy#8]
Hi,

When running the proxy, I get this message:

> listening on 0.0.0.0:9339 ...
> connection from 192.168.0.254:5828 ...
> connected to 184.73.10.78:9339 ...
> ClientHandshake: {
>   "unknown_0": 1,
>   "unknown_1": 7,
>   "majorVersion": 8,
>   "unknown_3": 0,
>   "minorVersion": 212,
>   "masterHash": "6e74f2d8c1728a567eadae278d0bb9c9eec42293",
>   "unknown_6": 2,
>   "unknown_7": 2
> }
> ServerHandshake: {
>   "sessionKey": "5b1aae65c979d4a470806f1ec6bee3bfb0717dc74386b365"
> }
> Failed to decrypt the message (server, 10101).
> connection from 192.168.0.254:5828 closed ...
> connection to 184.73.10.78:9339 closed ...

I run CoC in BlueStacks and have patched libg.so using my own method (C# program) because I don't want to install Android tools. I replaced key "469b...f419" by key "72f1...c27e" at offset 4280344. Here is the md5sum of my patched libs.so : 

> 0a5ea5d22282a4a0d9d9b51192abca78  libg.so

I don't see what's wrong. Help would be greatly appreciated. Thanks in advance.

**Comment by 123456abcdef** [comment]
Bluestacks runs an x86 Android build, so you have to use the offset `6189080` and you have to patch the x86 libg.so!

**Comment by Izwal** [comment]
Mmm... I check the presence of the public key in the whole libg.so file before overwriting it and I'm sure that offset 4280344 is the right one. This is the only place in the file where I can find the official public key "469b...f419".

**Comment by FICTURE7** [comment]
Be sure to patch the `x86` libg.so also.

**Comment by clugh** [comment]
As the others said, the issue is you patched the wrong version of `libg.so`.  The APK ships with two versions: `x86` and `arm`.  You mentioned you're using Bluestacks, but you gave the `arm` offset above, while Bluestacks will use the `x86` version.

> using my own method (C# program) because I don't want to install Android tools

My suggestion would be to use [`coc-patcher`](https://github.com/clugh/coc-patcher), as it will help mitigate these types of issue.  If it works, then you'll know the issue is with your current patching method.

**Comment by Izwal** [comment]
Thanks for the hint. To be more accurate, I installed CoC in Bluestacks then patched the `libg.so` file that had just been installed in `/data/data/com.supercell.clashofclans/lib`. So it seems that Bluestacks uses the `arm` version in my case, which should not happen according to you. I will investigate further and let you know. Thanks again.

**Comment by Izwal** [comment]
I finally understood that one have to patch the APK file and then install patched APK file on a device.
Not to install official APK and then try to patch installed files...

So now I try to patch the APK file by using [coc-patcher](https://github.com/clugh/coc-patcher). On my computer the patch fails at the end:

> Decoding APK ...
> Checking AndroidManifest.xml ...
> Checking package ID ...
> Patching package ID ...
> Verifying package ID ...
> Checking libg.so ...
> Checking keys ...
> Checking URLs ...
> Patching keys ...
> Patching URLs ...
> Verifying keys ...
> Verifying URLs ...
> Backing up original APK ...
> Building APK ...
> ERROR: Failed to build com.supercell.clashofclans-8.212.9.

When launching `apktool` from command-line, I get this message:

> I: Using Apktool 2.0.2-dirty
> I: Checking whether sources has changed...
> I: Checking whether resources has changed...
> I: Building resources...
> ERROR: Asset package include '/home/izwal/apktool/framework/1.apk' not found.
> Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException:
> ...

To be continued...

**Comment by clugh** [comment]
See the [Frameworks](http://ibotpeaches.github.io/Apktool/documentation/#frameworks) section of the `apktool` docs.  If you continue to have issues, I'd suggest opening an issue on the `apktool` [repo](https://github.com/iBotPeaches/Apktool).
