### ISSUE TITLE
8.332.2 key offset?

### ISSUE THREAD

**Issue by zyxwvuts** [clugh/coc-proxy#9]
Any thoughts about the new key offset and/or if the same encryption methods work?

**Comment by s-a-t-o-r-a-r-e** [comment]
**Key:**  bb9ca4c6b52ecdb40267c3bcca03679201a403ef6230b9e488db949b58bc7479    (num = #9)
**Masterhash:**  caf5869bc1270ec51ebf6bd89089182ee0650774

**URL Offsets (base 10):**
arm:  3673234
x86:  4974129

**Key Offsets (base 10):**
arm: 4431896
x86: 6434840

**EDIT (16:58 UTC):** These are actually the offsets for 8.332.6 (oops)! Read [my comment two places](https://github.com/clugh/coc-proxy/issues/9#issuecomment-221491963) below for more info. In short: all the info is the same, except for URL offsets.

**Comment by s-a-t-o-r-a-r-e** [comment]
To answer the actual question: the encryption method _is_ the same, so your proxy and APK/IPA will need just small changes to the key in order to work properly. You can use the info above to make the necessary adjustments ^^

**Comment by s-a-t-o-r-a-r-e** [comment]
... I just had a little realization; you've written in your issue title '8.332.2,' though I provided the offsets for the current version which I happened to have at the time (8.332.6). Odd given that I'd updated before you made your issue post o.o

Below is the info for the slightly older v8.332.2:

**Key:** bb9ca4c6b52ecdb40267c3bcca03679201a403ef6230b9e488db949b58bc7479 (same as 8.332.6)
**Masterhash:** caf5869bc1270ec51ebf6bd89089182ee0650774  (also the same as in 8.332.6)

**URL Offsets (base 10):**
arm: 3672818
x86: 4973505

**Key Offsets (base 10)**
arm: 4431896 (also the same as in 8.332.6)
x86: 6434840 (...you guessed it–it's the same...)

As you can see, only the URL offsets really changed between the two, so the original post I'd made contained pretty much anything you would need to get running with your proxy/server. Weird little error on my part, and a weird little patch.

~ Sorry about that.

**Comment by waqasrana** [comment]
and we have another update

8.332.9

**Comment by s-a-t-o-r-a-r-e** [comment]
Alright, this new update is kind of weird, mostly in the sense that it is labelled as 8.332.9, but the internal version is actually 8.332.4. Most of the stuff remained unchanged, so now I'll just add special indicators (in parentheses) of _only things which have changed_.

**Read Version:** 8.332.9
**Internal Version:** 8.332.4 (oddly decreases–use this for any sort of headless client)

**Key:** bb9ca4c6b52ecdb40267c3bcca03679201a403ef6230b9e488db949b58bc7479
**Masterhash:** 0e2aa6437fd507366473bc4450fbeba81d4af796 _(changed)_

**URL Offsets (base 10):**
arm:  3673378 _(changed)_
x86:  4974321 _(changed)_

**Key Offsets (base 10):**
arm:  4431896
x86:  6434840

Aaanyway, as you can see it's only the URL offsets and the masterhash that have changed, so proxies should work just fine, but you might need to make adjustments for any clients you have setup to run, depending on how you have them update.

**Comment by Ousret** [comment]
Anyone know what are PublicKey and PrivateKey as of today ?
Trying to get coc-proxy working.

Thank.

**Comment by Ousret** [comment]
Can we decrypt packet only using PublicKey ?
I'm bit of confused regarding CoC handshake.

**Comment by s-a-t-o-r-a-r-e** [comment]
@Ousret, of course ^^

It's a bit lengthy to explain things entirely in just this comment here (and frankly, I'm rather tired at the moment), but you can read up a bit on [asymmetric cryptography](https://en.wikipedia.org/wiki/Public-key_cryptography) for more info as for how this works, and take a peek through 'coc/server/crypto.py' for some actual application of the method.

I hope that helped, at least a bit ^^ !

(If you've any further questions, I do hope that you would create a separate issue next time, since this thread is already a bit messy. Thanks!)

**Comment by dchanda** [comment]
Hi Guys, any thoughts about the offset and the Key for version 8.332.16 ? For x86 and arm ?

**Comment by FICTURE7** [comment]
@dchanda, I already posted them on issue #12.

**Comment by ghost** [comment]
@s-a-t-o-r-a-r-e  do you have a clash of clans headless client?

**Comment by s-a-t-o-r-a-r-e** [comment]
@pochupin yes, I've been maintaining one for quite some time, as ClanSeeker went down (and really wasn't very good or stable in the first place). It's not OSS though, and won't translate easily to C#/Java/Python anyway, as it's natively built.

Sorry I couldn't help you more on that...

**Comment by ghost** [comment]
what is it used for @s-a-t-o-r-a-r-e  ?

**Comment by s-a-t-o-r-a-r-e** [comment]
@pochupin general data scraping. Originally it was meant to serve for a bot, but I haven't maintained that portion, and don't plan to any time soon.
